version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - ./envs/.account.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    name: mongo
