version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    env_file:
      - ./envs/.account.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  mongo:
    name: mongo
